In [7]:
import numpy as np
a=np.array([1,2,3,4,5])
print(a)
dimension=a.ndim
print("Dimension of array is:  {} ".format(dimension))
for i in a:
  print(i)

[1 2 3 4 5]
Dimension of array is:  1 
1
2
3
4
5


In [10]:
print(a[0]) #index
print(a[-3:])
print(a.size) # size of the 1d array
print(a.shape) # form of the array or matrix
print(a[-3:])

1
[3 4 5]
5
(5,)
[3 4 5]


In [11]:
a=np.array([1,2,3,4,5] , dtype=complex)
print(a)

[1.+0.j 2.+0.j 3.+0.j 4.+0.j 5.+0.j]


In [13]:
#2D array
b=np.array([[1,2,3,4],[5,6,7,8]])
print(b)
print(b.ndim)
#size
print(b.size)
print(b.shape)
print(b[1][2]) #b[row][column]

[[1 2 3 4]
 [5 6 7 8]]
2
8
(2, 4)
7


In [14]:
a=np.array([1,2,3,4,5], ndmin=2)
print(a)

[[1 2 3 4 5]]


In [19]:
#extra
a = np.array([[1,2,3],[3,4,5],[4,5,6]]) 

print ('Our array is:') 
print(a) 
print ('\n')  

# this returns array of items in the second column 
print ('The items in the second column are:')  
print (a[...,1] )
print ('\n')  

# Now we will slice all items from the second row 
print('The items in the second row are:' )
print(a[1,...] )
print ('\n')  



Our array is:
[[1 2 3]
 [3 4 5]
 [4 5 6]]


The items in the second column are:
[2 4 5]


The items in the second row are:
[3 4 5]




In [21]:
c=np.array([[[1,2,3],[3,4,5]],[[1,2,3],[3,4,5]]])
print(c)
print(c[0][1][1]) #slicing

[[[1 2 3]
  [3 4 5]]

 [[1 2 3]
  [3 4 5]]]
4


In [3]:
#addition of two 1-D matrix
a=np.array([1,2,3,4,5])
b=np.array([6,7,8,9,9])
c=a+b
for i in c:
  print(i)

NameError: name 'np' is not defined

In [ ]:

a=np.arange(24)
c=a.reshape(3,8) # reshape 
b=a.reshape(3,2,4)
print(b.ndim)
print(b)
print(b[1][1][1])

In [24]:
a=np.arange(9)  #2D Array
c=a.reshape(3,3)
print(c.ndim)
print(c) 

2
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [25]:
a=np.empty([2,2],dtype=int)
print(a)
print(a.ndim)
print(a[1][1])

[[1 2]
 [3 4]]
2
4


In [26]:
a=np.zeros([2,3])
print(a)
b=np.ones([4,5])
print(b)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [4]:
import numpy as np
#a=np.arange(4).reshape(2,2)
#b=np.arange(4).reshape(2,2)
a=np.array([[0,1],[2,3]])
b=np.array([[0,1],[2,3]])
print(a)
print(b)
#print(a*b)
print("multiplication of your matrix is  : " , np.dot(a,b))

[[0 1]
 [2 3]]
[[0 1]
 [2 3]]
[[0 1]
 [4 9]]
multiplication of your matrix is  :  [[ 2  3]
 [ 6 11]]


In [5]:
a=np.array([1,2,3,4])
b=np.array([1,2,3,4])
print(a*b)

[ 1  4  9 16]
