In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [11]:
df=pd.read_csv(r"C:\Users\Hritik\Desktop\iris_data.csv")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal.length  150 non-null    float64
 1   sepal.width   150 non-null    float64
 2   petal.length  150 non-null    float64
 3   petal.width   150 non-null    float64
 4   variety       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 5.3+ KB


In [3]:
df.head()

sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa

In [4]:
x=df.iloc[:,0:-1]
x.head()

sepal.length  sepal.width  petal.length  petal.width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2
2           4.7          3.2           1.3          0.2
3           4.6          3.1           1.5          0.2
4           5.0          3.6           1.4          0.2

In [6]:
y=df.iloc[:,4]
y.head()

0    Setosa
1    Setosa
2    Setosa
3    Setosa
4    Setosa
Name: variety, dtype: object

In [7]:
from sklearn.model_selection import train_test_split

In [8]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=1)

In [22]:
x_train

sepal.length  sepal.width  petal.length  petal.width
91            6.1          3.0           4.6          1.4
135           7.7          3.0           6.1          2.3
69            5.6          2.5           3.9          1.1
128           6.4          2.8           5.6          2.1
114           5.8          2.8           5.1          2.4
..            ...          ...           ...          ...
133           6.3          2.8           5.1          1.5
137           6.4          3.1           5.5          1.8
72            6.3          2.5           4.9          1.5
140           6.7          3.1           5.6          2.4
37            4.9          3.6           1.4          0.1

[120 rows x 4 columns]

In [14]:
x_test.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 30 entries, 14 to 146
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal.length  30 non-null     float64
 1   sepal.width   30 non-null     float64
 2   petal.length  30 non-null     float64
 3   petal.width   30 non-null     float64
dtypes: float64(4)
memory usage: 1.2 KB


In [15]:
from sklearn.preprocessing import StandardScaler

In [19]:
scalar=StandardScaler()

In [20]:
scalar.fit(x_train)

StandardScaler()

In [21]:
x_train

sepal.length  sepal.width  petal.length  petal.width
91            6.1          3.0           4.6          1.4
135           7.7          3.0           6.1          2.3
69            5.6          2.5           3.9          1.1
128           6.4          2.8           5.6          2.1
114           5.8          2.8           5.1          2.4
..            ...          ...           ...          ...
133           6.3          2.8           5.1          1.5
137           6.4          3.1           5.5          1.8
72            6.3          2.5           4.9          1.5
140           6.7          3.1           5.6          2.4
37            4.9          3.6           1.4          0.1

[120 rows x 4 columns]

In [26]:
x_train=scalar.transform(x_train)

In [27]:
x_test=scalar.transform(x_test)

In [30]:
x_train

array([[-15.07114024, -24.70518304,  -3.23876315,  -3.22345356],
       [-12.26555107, -24.70518304,  -2.9658029 ,  -1.27829279],
       [-15.94788686, -31.52243688,  -3.3661446 ,  -3.87184049],
       [-14.54509227, -27.43208457,  -3.05678965,  -1.71055074],
       [-15.59718822, -27.43208457,  -3.1477764 ,  -1.06216381],
       [-16.47393483, -15.16102766,  -3.80288099,  -5.81700126],
       [-16.12323619, -34.24933841,  -3.34794725,  -3.43958254],
       [-16.64928416, -19.25137997,  -3.82107834,  -5.81700126],
       [-14.36974295, -27.43208457,  -3.23876315,  -3.00732459],
       [-14.0190443 , -31.52243688,  -3.02039495,  -2.35893766],
       [-13.84369498, -24.70518304,  -3.074987  ,  -1.71055074],
       [-16.82463348, -17.8879292 ,  -3.82107834,  -5.60087228],
       [-15.24648957, -35.61278918,  -3.16597375,  -3.00732459],
       [-14.7204416 , -26.06863381,  -3.05678965,  -2.35893766],
       [-14.19439363, -26.06863381,  -3.23876315,  -3.43958254],
       [-12.26555107, -30

In [32]:
from sklearn.neighbors import KNeighborsClassifier
classifier=KNeighborsClassifier(n_neighbors=5)
classifier.fit(x_train,y_train)

KNeighborsClassifier()

In [33]:
yp=classifier.predict(x_test)

In [35]:
from sklearn import metrics
print(metrics.confusion_matrix(y_test,yp))

[[11  0  0]
 [13  0  0]
 [ 6  0  0]]


In [36]:
print(metrics.classification_report(y_test,yp))

              precision    recall  f1-score   support

      Setosa       0.37      1.00      0.54        11
  Versicolor       0.00      0.00      0.00        13
   Virginica       0.00      0.00      0.00         6

    accuracy                           0.37        30
   macro avg       0.12      0.33      0.18        30
weighted avg       0.13      0.37      0.20        30



C:\Users\Hritik\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
